### ISSUE TITLE
Need to add example on how to use R CMD CHECK against bleeding edge repos

### ISSUE THREAD

**Issue by epijim** [phuse-org/devops#14]
Currently we have:

## How do I set it up?

Below is an example of using this `gh-action` whenever someone tries to make PR into your `main` or `devel` branch or updates the branch. We recomend you use this on both `main` and `devel` branches, as it will help you catch issues before they get into your main branch.

```yaml
name: Run R-CMD-check
# sourced from phuse-org/devops-toolkit

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    name: Check
    uses: phuse-org/devops-toolkit/.github/workflows/R-CMD-check.yml@main
```

## Advanced use

TODO: Add here how to also run against pharmaverse's r-universe latest & the latest release of PPM packages.
```
